import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    'index':                'src/index.ts',
    'prelude/index':        'src/prelude/index.ts',
    'prelude/types':        'src/prelude/types.ts',
    'prelude/identity':     'src/prelude/identity.ts',
    'prelude/constant':     'src/prelude/constant.ts',
    'prelude/pipe':         'src/prelude/pipe.ts',
    'prelude/flow':         'src/prelude/flow.ts',
    'prelude/guard':        'src/prelude/guard.ts',
    'prelude/monoid':       'src/prelude/monoid.ts',
    'monad/continuation':   'src/monad/continuation.ts',
    'monad/maybe':          'src/monad/maybe.ts',
    'monad/result':         'src/monad/result.ts',
    'monad/either':         'src/monad/either.ts',
    'monad/identity':       'src/monad/identity.ts',
    'monad/io':             'src/monad/io.ts',
    'monad/reader':         'src/monad/reader.ts',
    'monad/state':          'src/monad/state.ts',
    'monad/writer':         'src/monad/writer.ts',
    'monad/list':           'src/monad/list.ts',
    'monad/tree':           'src/monad/tree.ts',
    'monad/logic':          'src/monad/logic.ts',
    'monad/task':           'src/monad/task.ts',
    'monad/distribution':   'src/monad/distribution.ts',
    'monad/parser':         'src/monad/parser.ts',
    'monad/observable':     'src/monad/observable.ts',
    'monad/convert':    'src/monad/convert.ts',
  },
  outDir: 'dist',
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  sourcemap: true,
  splitting: false,
  bundle: false,
})
